-- Auto-generated by scripts/generate-storage-buckets-sql.mjs from storage-buckets.manifest.json
-- Do not edit this file by hand; change the manifest and re-run the generator.
--
-- Run once in Supabase SQL Editor (same project as your app .env).
-- Idempotent: safe to re-run; updates public / size limit / MIME allowlist on conflict.
--
-- App references:
--   listing-images   → app/api/listings, app/api/listings/[id]
--   dispute-evidence → lib/evidenceUpload.js
--
-- Next: run 022_storage_objects_policies_safe_hands.sql so storage.objects RLS matches these buckets.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'listing-images',
    'listing-images',
    true,
    5242880,
    NULL
  ),
  (
    'dispute-evidence',
    'dispute-evidence',
    true,
    5242880,
    ARRAY['image/jpeg', 'image/png', 'image/webp']::text[]
  )
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

SELECT id, name, public, file_size_limit, allowed_mime_types, created_at
FROM storage.buckets
WHERE id = ANY (ARRAY['listing-images', 'dispute-evidence']::text[])
ORDER BY id;
